version: '3.1'

services:
  db:
    image: postgres:10
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: universal_weather
